* sconesite/image: New image manipulation module   using Image/GraphicsMagick (libMagick++). * sconesite/Article: Add remove_file arg method. * sconesite/ArgFile: Move ArgFile class to own file. * all: Reduce some unneccecary linkage.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -882,6 +882,8 @@ F77
 FFLAGS
 ac_ct_F77
 LIBTOOL
+SSL_LIBADD
+SCONESITE_IMAGE_LIBADD
 LIBOBJS
 BUILD_ROUTER_IP_TRUE
 BUILD_ROUTER_IP_FALSE
@@ -901,6 +903,8 @@ BUILD_LETTUCE_TRUE
 BUILD_LETTUCE_FALSE
 BUILD_SCONESITE_TRUE
 BUILD_SCONESITE_FALSE
+BUILD_SCONESITE_IMAGE_TRUE
+BUILD_SCONESITE_IMAGE_FALSE
 LTLIBOBJS'
 ac_subst_files=''
       ac_precious_vars='build_alias
@@ -1526,6 +1530,7 @@ Optional Packages:
   --with-testbuilder      Enable TestBuilder module
   --with-lettuce          Enable Lettuce module
   --with-sconesite        Enable Sconesite module
+  --with-sconesite-image  Enable Sconesite:image module
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -5350,7 +5355,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5353 "configure"' > conftest.$ac_ext
+  echo '#line 5358 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7705,11 +7710,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7708: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7713: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7712: \$? = $ac_status" >&5
+   echo "$as_me:7717: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7995,11 +8000,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7998: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8003: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8002: \$? = $ac_status" >&5
+   echo "$as_me:8007: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8099,11 +8104,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8102: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8107: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8106: \$? = $ac_status" >&5
+   echo "$as_me:8111: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10476,7 +10481,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10479 "configure"
+#line 10484 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10576,7 +10581,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10579 "configure"
+#line 10584 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12977,11 +12982,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12980: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12985: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12984: \$? = $ac_status" >&5
+   echo "$as_me:12989: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13081,11 +13086,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13084: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13089: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13088: \$? = $ac_status" >&5
+   echo "$as_me:13093: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14679,11 +14684,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14682: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14687: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14686: \$? = $ac_status" >&5
+   echo "$as_me:14691: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14783,11 +14788,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14786: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14791: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14790: \$? = $ac_status" >&5
+   echo "$as_me:14795: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17003,11 +17008,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17006: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17011: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17010: \$? = $ac_status" >&5
+   echo "$as_me:17015: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17293,11 +17298,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17296: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17301: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17300: \$? = $ac_status" >&5
+   echo "$as_me:17305: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17397,11 +17402,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17400: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17405: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17404: \$? = $ac_status" >&5
+   echo "$as_me:17409: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21033,7 +21038,7 @@ fi
 
 # Check whether --with-openssl_path was given.
 if test "${with_openssl_path+set}" = set; then
-  withval=$with_openssl_path; CPPFLAGS="$CPPFLAGS -I$withval/include"; LDFLAGS="$LDFLAGS -L$withval/lib"
+  withval=$with_openssl_path; CPPFLAGS="$CPPFLAGS -I$withval/include";
 fi
 
 
@@ -21322,8 +21327,7 @@ echo "$as_me: error: header file <openssl/ssl.h> is required for OpenSSL, use --
 fi
 
 
-
-{ echo "$as_me:$LINENO: checking for CRYPTO_new_ex_data in -lcrypto" >&5
+  { echo "$as_me:$LINENO: checking for CRYPTO_new_ex_data in -lcrypto" >&5
 echo $ECHO_N "checking for CRYPTO_new_ex_data in -lcrypto... $ECHO_C" >&6; }
 if test "${ac_cv_lib_crypto_CRYPTO_new_ex_data+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -21385,12 +21389,7 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_crypto_CRYPTO_new_ex_data" >&5
 echo "${ECHO_T}$ac_cv_lib_crypto_CRYPTO_new_ex_data" >&6; }
 if test $ac_cv_lib_crypto_CRYPTO_new_ex_data = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBCRYPTO 1
-_ACEOF
-
-  LIBS="-lcrypto $LIBS"
-
+  SSL_LIBADD="$SSL_LIBADD -lcrypto"
 else
   { { echo "$as_me:$LINENO: error: library 'crypto' is required for OpenSSL" >&5
 echo "$as_me: error: library 'crypto' is required for OpenSSL" >&2;}
@@ -21398,8 +21397,7 @@ echo "$as_me: error: library 'crypto' is required for OpenSSL" >&2;}
 
 fi
 
-
-{ echo "$as_me:$LINENO: checking for SSL_library_init in -lssl" >&5
+  { echo "$as_me:$LINENO: checking for SSL_library_init in -lssl" >&5
 echo $ECHO_N "checking for SSL_library_init in -lssl... $ECHO_C" >&6; }
 if test "${ac_cv_lib_ssl_SSL_library_init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -21461,18 +21459,14 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_ssl_SSL_library_init" >&5
 echo "${ECHO_T}$ac_cv_lib_ssl_SSL_library_init" >&6; }
 if test $ac_cv_lib_ssl_SSL_library_init = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBSSL 1
-_ACEOF
-
-  LIBS="-lssl $LIBS"
-
+  SSL_LIBADD="$SSL_LIBADD -lssl"
 else
   { { echo "$as_me:$LINENO: error: library 'ssl' is required for OpenSSL" >&5
 echo "$as_me: error: library 'ssl' is required for OpenSSL" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
+
 
 fi
 
@@ -21593,6 +21587,93 @@ echo "$as_me: error: library 'xml2' is required for Sconesite" >&2;}
 fi
 
 fi
+
+# Sconesite:image module
+
+# Check whether --with-sconesite-image was given.
+if test "${with_sconesite_image+set}" = set; then
+  withval=$with_sconesite_image; SCONESITE_IMAGE="$withval"
+else
+  SCONESITE_IMAGE="yes"
+
+fi
+
+# Need ImageMagick for Sconesite:image
+if test "x$SCONESITE_IMAGE" == "xyes"; then
+  { echo "$as_me:$LINENO: checking for InitializeMagick in -lMagick++" >&5
+echo $ECHO_N "checking for InitializeMagick in -lMagick++... $ECHO_C" >&6; }
+if test "${ac_cv_lib_Magickpp_InitializeMagick+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lMagick++  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char InitializeMagick ();
+int
+main ()
+{
+return InitializeMagick ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_Magickpp_InitializeMagick=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_Magickpp_InitializeMagick=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_Magickpp_InitializeMagick" >&5
+echo "${ECHO_T}$ac_cv_lib_Magickpp_InitializeMagick" >&6; }
+if test $ac_cv_lib_Magickpp_InitializeMagick = yes; then
+  CPPFLAGS="$CPPFLAGS `Magick++-config --cppflags`"
+     SCONESITE_IMAGE_LIBADD=`Magick++-config --libs`
+
+else
+  { { echo "$as_me:$LINENO: error: library 'Magick++' is required for Sconesite:image" >&5
+echo "$as_me: error: library 'Magick++' is required for Sconesite:image" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+fi
+
 
 # Checks for header files.
 ac_ext=cpp
@@ -25466,6 +25547,14 @@ else
   BUILD_SCONESITE_FALSE=
 fi
 
+ if test x$SCONESITE_IMAGE = xyes; then
+  BUILD_SCONESITE_IMAGE_TRUE=
+  BUILD_SCONESITE_IMAGE_FALSE='#'
+else
+  BUILD_SCONESITE_IMAGE_TRUE='#'
+  BUILD_SCONESITE_IMAGE_FALSE=
+fi
+
 
 CPPFLAGS="$CPPFLAGS -Wall"
 
@@ -25522,6 +25611,8 @@ ac_config_files="$ac_config_files testbuilder/Makefile"
 ac_config_files="$ac_config_files lettuce/Makefile"
 
 ac_config_files="$ac_config_files sconesite/Makefile"
+
+ac_config_files="$ac_config_files sconesite/image/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -25708,6 +25799,13 @@ if test -z "${BUILD_SCONESITE_TRUE}" && test -z "${BUILD_SCONESITE_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_SCONESITE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_SCONESITE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_SCONESITE_IMAGE_TRUE}" && test -z "${BUILD_SCONESITE_IMAGE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_SCONESITE_IMAGE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_SCONESITE_IMAGE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -26207,6 +26305,7 @@ do
     "testbuilder/Makefile") CONFIG_FILES="$CONFIG_FILES testbuilder/Makefile" ;;
     "lettuce/Makefile") CONFIG_FILES="$CONFIG_FILES lettuce/Makefile" ;;
     "sconesite/Makefile") CONFIG_FILES="$CONFIG_FILES sconesite/Makefile" ;;
+    "sconesite/image/Makefile") CONFIG_FILES="$CONFIG_FILES sconesite/image/Makefile" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -26421,6 +26520,8 @@ F77!$F77$ac_delim
 FFLAGS!$FFLAGS$ac_delim
 ac_ct_F77!$ac_ct_F77$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
+SSL_LIBADD!$SSL_LIBADD$ac_delim
+SCONESITE_IMAGE_LIBADD!$SCONESITE_IMAGE_LIBADD$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 BUILD_ROUTER_IP_TRUE!$BUILD_ROUTER_IP_TRUE$ac_delim
 BUILD_ROUTER_IP_FALSE!$BUILD_ROUTER_IP_FALSE$ac_delim
@@ -26440,10 +26541,12 @@ BUILD_LETTUCE_TRUE!$BUILD_LETTUCE_TRUE$ac_delim
 BUILD_LETTUCE_FALSE!$BUILD_LETTUCE_FALSE$ac_delim
 BUILD_SCONESITE_TRUE!$BUILD_SCONESITE_TRUE$ac_delim
 BUILD_SCONESITE_FALSE!$BUILD_SCONESITE_FALSE$ac_delim
+BUILD_SCONESITE_IMAGE_TRUE!$BUILD_SCONESITE_IMAGE_TRUE$ac_delim
+BUILD_SCONESITE_IMAGE_FALSE!$BUILD_SCONESITE_IMAGE_FALSE$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 34; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 38; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -27064,6 +27167,8 @@ The following modules will be built:
     + getfile      yes
     + dirindex     yes
     + errorpage    yes
+    + sconesite    $SCONESITE
+      + image      $SCONESITE_IMAGE
   + ssl            $SSL
   + exec           yes
   + forward        yes
@@ -27072,7 +27177,6 @@ The following modules will be built:
   + examples       $EXAMPLES
   + testbuilder    $TESTBUILDER
   + lettuce        $LETTUCE
-  + sconesite      $SCONESITE
 " >&5
 echo "${ECHO_T}
 ------------------------------------------------------------------------------
@@ -27095,6 +27199,8 @@ The following modules will be built:
     + getfile      yes
     + dirindex     yes
     + errorpage    yes
+    + sconesite    $SCONESITE
+      + image      $SCONESITE_IMAGE
   + ssl            $SSL
   + exec           yes
   + forward        yes
@@ -27103,5 +27209,4 @@ The following modules will be built:
   + examples       $EXAMPLES
   + testbuilder    $TESTBUILDER
   + lettuce        $LETTUCE
-  + sconesite      $SCONESITE
 " >&6; }
