* sconex/MimeHeader: Move line parsing into here from http::Request. * sconesite: Linking against libxml2 for XML parsing. * sconesite/XMLDoc: New base class XML document parser. * sconesite/Article: New article class. * sconesite/Template: New doc template class. * sconesite/Profile: New site profile, holds templates and articles. * sconesite/Context: New xml processing context base class.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21697,12 +21697,94 @@ else
 fi
 
 ## if we use libxml for sconesite:
-#if test "x$SCONESITE" == "xyes"; then
-#  AC_CHECK_LIB([xml2],[xmlNewDoc],,
-#    [AC_MSG_ERROR([library 'xml2' is required for Sconesite])]
-#  )
-#  CPPFLAGS = "$CPPFLAGS `xml2-config --cflags`";
-#fi
+if test "x$SCONESITE" == "xyes"; then
+  { echo "$as_me:$LINENO: checking for xmlNewDoc in -lxml2" >&5
+echo $ECHO_N "checking for xmlNewDoc in -lxml2... $ECHO_C" >&6; }
+if test "${ac_cv_lib_xml2_xmlNewDoc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lxml2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char xmlNewDoc ();
+int
+main ()
+{
+return xmlNewDoc ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_xml2_xmlNewDoc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_xml2_xmlNewDoc=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_xml2_xmlNewDoc" >&5
+echo "${ECHO_T}$ac_cv_lib_xml2_xmlNewDoc" >&6; }
+if test $ac_cv_lib_xml2_xmlNewDoc = yes; then
+  CPPFLAGS="$CPPFLAGS `xml2-config --cflags`"
+else
+  { { echo "$as_me:$LINENO: error: library 'xml2' is required for Sconesite" >&5
+echo "$as_me: error: library 'xml2' is required for Sconesite" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+fi
 
 # Checks for header files.
 ac_ext=cpp
