* dbsql: Use mysqlclient c lib instead of MySql++. * sconesite/SconesiteModule: Correct authorization check.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21763,15 +21763,15 @@ else
 
 fi
 
-# Need MySql++ library for dbsql
+# Need mysqlclient library for dbsql
 if test "x$DBSQL" == "xyes"; then
-  { echo "$as_me:$LINENO: checking for main in -lmysqlpp" >&5
-echo $ECHO_N "checking for main in -lmysqlpp... $ECHO_C" >&6; }
-if test "${ac_cv_lib_mysqlpp_main+set}" = set; then
+  { echo "$as_me:$LINENO: checking for mysql_init in -lmysqlclient" >&5
+echo $ECHO_N "checking for mysql_init in -lmysqlclient... $ECHO_C" >&6; }
+if test "${ac_cv_lib_mysqlclient_mysql_init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmysqlpp  $LIBS"
+LIBS="-lmysqlclient  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -21779,11 +21779,17 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char mysql_init ();
 int
 main ()
 {
-return main ();
+return mysql_init ();
   ;
   return 0;
 }
@@ -21806,27 +21812,27 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_mysqlpp_main=yes
+  ac_cv_lib_mysqlclient_mysql_init=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_mysqlpp_main=no
+	ac_cv_lib_mysqlclient_mysql_init=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlpp_main" >&5
-echo "${ECHO_T}$ac_cv_lib_mysqlpp_main" >&6; }
-if test $ac_cv_lib_mysqlpp_main = yes; then
-  CPPFLAGS="$CPPFLAGS -I/usr/include/mysql++ -I/usr/include/mysql"
-     DBSQL_LIBADD="-lmysqlpp"
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_mysql_init" >&5
+echo "${ECHO_T}$ac_cv_lib_mysqlclient_mysql_init" >&6; }
+if test $ac_cv_lib_mysqlclient_mysql_init = yes; then
+  CPPFLAGS="$CPPFLAGS -I/usr/include/mysql"
+     DBSQL_LIBADD="-lmysqlclient"
 
 else
-  { { echo "$as_me:$LINENO: error: library 'MySql++' is required for dbsql" >&5
-echo "$as_me: error: library 'MySql++' is required for dbsql" >&2;}
+  { { echo "$as_me:$LINENO: error: library 'mysqlclient' is required for dbsql" >&5
+echo "$as_me: error: library 'mysqlclient' is required for dbsql" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
