* sconesite: Relocate from root to http subdirectory. * sconesite/rss: New RSS/Atom feed (client) module. * http/Session: Clean up job name and timeout. * sconesite/SconesiteModule: Clean up job name and timeout. * sconesite/RenderMarkup: Support multiple options in   process_article(). Add base_url option for links. * sconex/Uri: Add base() method for getting base part of Uri. * sconex/ModuleLoaderDLL: Improve dev mode module searching. * all: Rationalise module naming, now same as directory.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -907,6 +907,8 @@ BUILD_SCONESITE_TRUE
 BUILD_SCONESITE_FALSE
 BUILD_SCONESITE_IMAGE_TRUE
 BUILD_SCONESITE_IMAGE_FALSE
+BUILD_SCONESITE_RSS_TRUE
+BUILD_SCONESITE_RSS_FALSE
 BUILD_DBSQL_TRUE
 BUILD_DBSQL_FALSE
 LTLIBOBJS'
@@ -1535,6 +1537,7 @@ Optional Packages:
   --with-lettuce          Enable Lettuce module
   --with-sconesite        Enable Sconesite module
   --with-sconesite-image  Enable Sconesite:image module
+  --with-sconesite-rss    Enable Sconesite:rss module
   --with-dbsql            Enable SQL Database module
 
 Some influential environment variables:
@@ -5360,7 +5363,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5363 "configure"' > conftest.$ac_ext
+  echo '#line 5366 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7715,11 +7718,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7718: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7721: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7722: \$? = $ac_status" >&5
+   echo "$as_me:7725: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8005,11 +8008,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8008: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8011: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8012: \$? = $ac_status" >&5
+   echo "$as_me:8015: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8109,11 +8112,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8112: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8115: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8116: \$? = $ac_status" >&5
+   echo "$as_me:8119: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10486,7 +10489,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10489 "configure"
+#line 10492 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10586,7 +10589,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10589 "configure"
+#line 10592 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12987,11 +12990,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12990: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12993: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12994: \$? = $ac_status" >&5
+   echo "$as_me:12997: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13091,11 +13094,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13094: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13097: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13098: \$? = $ac_status" >&5
+   echo "$as_me:13101: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14689,11 +14692,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14692: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14695: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14696: \$? = $ac_status" >&5
+   echo "$as_me:14699: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14793,11 +14796,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14796: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14799: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14800: \$? = $ac_status" >&5
+   echo "$as_me:14803: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17013,11 +17016,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17016: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17019: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17020: \$? = $ac_status" >&5
+   echo "$as_me:17023: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17303,11 +17306,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17306: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17309: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17310: \$? = $ac_status" >&5
+   echo "$as_me:17313: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17407,11 +17410,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17410: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17413: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17414: \$? = $ac_status" >&5
+   echo "$as_me:17417: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21824,6 +21827,17 @@ fi
 
 fi
 
+# Sconesite:rss module
+
+# Check whether --with-sconesite-rss was given.
+if test "${with_sconesite_rss+set}" = set; then
+  withval=$with_sconesite_rss; SCONESITE_RSS="$withval"
+else
+  SCONESITE_RSS="yes"
+
+fi
+
+
 # DbSql module
 
 # Check whether --with-dbsql was given.
@@ -26228,6 +26242,14 @@ else
   BUILD_SCONESITE_IMAGE_FALSE=
 fi
 
+ if test x$SCONESITE_RSS = xyes; then
+  BUILD_SCONESITE_RSS_TRUE=
+  BUILD_SCONESITE_RSS_FALSE='#'
+else
+  BUILD_SCONESITE_RSS_TRUE='#'
+  BUILD_SCONESITE_RSS_FALSE=
+fi
+
  if test x$DBSQL = xyes; then
   BUILD_DBSQL_TRUE=
   BUILD_DBSQL_FALSE='#'
@@ -26277,6 +26299,12 @@ ac_config_files="$ac_config_files http/dirindex/Makefile"
 
 ac_config_files="$ac_config_files http/errorpage/Makefile"
 
+ac_config_files="$ac_config_files http/sconesite/Makefile"
+
+ac_config_files="$ac_config_files http/sconesite/image/Makefile"
+
+ac_config_files="$ac_config_files http/sconesite/rss/Makefile"
+
 ac_config_files="$ac_config_files exec/Makefile"
 
 ac_config_files="$ac_config_files forward/Makefile"
@@ -26288,10 +26316,6 @@ ac_config_files="$ac_config_files test/Makefile"
 ac_config_files="$ac_config_files testbuilder/Makefile"
 
 ac_config_files="$ac_config_files lettuce/Makefile"
-
-ac_config_files="$ac_config_files sconesite/Makefile"
-
-ac_config_files="$ac_config_files sconesite/image/Makefile"
 
 ac_config_files="$ac_config_files dbsql/Makefile"
 
@@ -26487,6 +26511,13 @@ if test -z "${BUILD_SCONESITE_IMAGE_TRUE}" && test -z "${BUILD_SCONESITE_IMAGE_F
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_SCONESITE_IMAGE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_SCONESITE_IMAGE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_SCONESITE_RSS_TRUE}" && test -z "${BUILD_SCONESITE_RSS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_SCONESITE_RSS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_SCONESITE_RSS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -26985,14 +27016,15 @@ do
     "http/getfile/Makefile") CONFIG_FILES="$CONFIG_FILES http/getfile/Makefile" ;;
     "http/dirindex/Makefile") CONFIG_FILES="$CONFIG_FILES http/dirindex/Makefile" ;;
     "http/errorpage/Makefile") CONFIG_FILES="$CONFIG_FILES http/errorpage/Makefile" ;;
+    "http/sconesite/Makefile") CONFIG_FILES="$CONFIG_FILES http/sconesite/Makefile" ;;
+    "http/sconesite/image/Makefile") CONFIG_FILES="$CONFIG_FILES http/sconesite/image/Makefile" ;;
+    "http/sconesite/rss/Makefile") CONFIG_FILES="$CONFIG_FILES http/sconesite/rss/Makefile" ;;
     "exec/Makefile") CONFIG_FILES="$CONFIG_FILES exec/Makefile" ;;
     "forward/Makefile") CONFIG_FILES="$CONFIG_FILES forward/Makefile" ;;
     "tftp/Makefile") CONFIG_FILES="$CONFIG_FILES tftp/Makefile" ;;
     "test/Makefile") CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
     "testbuilder/Makefile") CONFIG_FILES="$CONFIG_FILES testbuilder/Makefile" ;;
     "lettuce/Makefile") CONFIG_FILES="$CONFIG_FILES lettuce/Makefile" ;;
-    "sconesite/Makefile") CONFIG_FILES="$CONFIG_FILES sconesite/Makefile" ;;
-    "sconesite/image/Makefile") CONFIG_FILES="$CONFIG_FILES sconesite/image/Makefile" ;;
     "dbsql/Makefile") CONFIG_FILES="$CONFIG_FILES dbsql/Makefile" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -27233,12 +27265,14 @@ BUILD_SCONESITE_TRUE!$BUILD_SCONESITE_TRUE$ac_delim
 BUILD_SCONESITE_FALSE!$BUILD_SCONESITE_FALSE$ac_delim
 BUILD_SCONESITE_IMAGE_TRUE!$BUILD_SCONESITE_IMAGE_TRUE$ac_delim
 BUILD_SCONESITE_IMAGE_FALSE!$BUILD_SCONESITE_IMAGE_FALSE$ac_delim
+BUILD_SCONESITE_RSS_TRUE!$BUILD_SCONESITE_RSS_TRUE$ac_delim
+BUILD_SCONESITE_RSS_FALSE!$BUILD_SCONESITE_RSS_FALSE$ac_delim
 BUILD_DBSQL_TRUE!$BUILD_DBSQL_TRUE$ac_delim
 BUILD_DBSQL_FALSE!$BUILD_DBSQL_FALSE$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 42; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 44; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -27861,6 +27895,7 @@ The following modules will be built:
     + errorpage    yes
     + sconesite    $SCONESITE
       + image      $SCONESITE_IMAGE
+      + rss        $SCONESITE_RSS
   + ssl            $SSL
   + exec           yes
   + forward        yes
@@ -27894,6 +27929,7 @@ The following modules will be built:
     + errorpage    yes
     + sconesite    $SCONESITE
       + image      $SCONESITE_IMAGE
+      + rss        $SCONESITE_RSS
   + ssl            $SSL
   + exec           yes
   + forward        yes
