* dbsql: New SQL Database interface module supporting MySQL. * configure: Add dbsql and check for MySql++ lib. * sconex/ConfigStream: Catch exceptions when evaluating. * sconesite/SconesiteModule: Check authorization for profile setup.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -885,6 +885,7 @@ LIBTOOL
 SSL_LIBADD
 SCONESITE_IMAGE_LIBADD
 SCONESITE_IMAGE_LDFLAGS
+DBSQL_LIBADD
 LIBOBJS
 BUILD_ROUTER_IP_TRUE
 BUILD_ROUTER_IP_FALSE
@@ -906,6 +907,8 @@ BUILD_SCONESITE_TRUE
 BUILD_SCONESITE_FALSE
 BUILD_SCONESITE_IMAGE_TRUE
 BUILD_SCONESITE_IMAGE_FALSE
+BUILD_DBSQL_TRUE
+BUILD_DBSQL_FALSE
 LTLIBOBJS'
 ac_subst_files=''
       ac_precious_vars='build_alias
@@ -1532,6 +1535,7 @@ Optional Packages:
   --with-lettuce          Enable Lettuce module
   --with-sconesite        Enable Sconesite module
   --with-sconesite-image  Enable Sconesite:image module
+  --with-dbsql            Enable SQL Database module
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -5356,7 +5360,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5359 "configure"' > conftest.$ac_ext
+  echo '#line 5363 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7711,11 +7715,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7714: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7718: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7718: \$? = $ac_status" >&5
+   echo "$as_me:7722: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8001,11 +8005,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8004: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8008: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8008: \$? = $ac_status" >&5
+   echo "$as_me:8012: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8105,11 +8109,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8108: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8112: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8112: \$? = $ac_status" >&5
+   echo "$as_me:8116: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10482,7 +10486,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10485 "configure"
+#line 10489 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10582,7 +10586,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10585 "configure"
+#line 10589 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12983,11 +12987,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12986: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12990: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12990: \$? = $ac_status" >&5
+   echo "$as_me:12994: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13087,11 +13091,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13090: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13094: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13094: \$? = $ac_status" >&5
+   echo "$as_me:13098: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14685,11 +14689,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14688: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14692: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14692: \$? = $ac_status" >&5
+   echo "$as_me:14696: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14789,11 +14793,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14792: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14796: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14796: \$? = $ac_status" >&5
+   echo "$as_me:14800: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17009,11 +17013,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17012: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17016: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17016: \$? = $ac_status" >&5
+   echo "$as_me:17020: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17299,11 +17303,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17302: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17306: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17306: \$? = $ac_status" >&5
+   echo "$as_me:17310: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17403,11 +17407,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17406: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17410: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17410: \$? = $ac_status" >&5
+   echo "$as_me:17414: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21671,7 +21675,7 @@ else
 
 fi
 
- Need ImageMagick for Sconesite:image
+# Need ImageMagick for Sconesite:image
 if test "x$SCONESITE_IMAGE" == "xyes"; then
   { echo "$as_me:$LINENO: checking for InitializeMagick in -lMagick++" >&5
 echo $ECHO_N "checking for InitializeMagick in -lMagick++... $ECHO_C" >&6; }
@@ -21743,6 +21747,86 @@ if test $ac_cv_lib_Magickpp_InitializeMagick = yes; then
 else
   { { echo "$as_me:$LINENO: error: library 'Magick++' is required for Sconesite:image" >&5
 echo "$as_me: error: library 'Magick++' is required for Sconesite:image" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+fi
+
+# DbSql module
+
+# Check whether --with-dbsql was given.
+if test "${with_dbsql+set}" = set; then
+  withval=$with_dbsql; DBSQL="$withval"
+else
+  DBSQL="yes"
+
+fi
+
+# Need MySql++ library for dbsql
+if test "x$DBSQL" == "xyes"; then
+  { echo "$as_me:$LINENO: checking for main in -lmysqlpp" >&5
+echo $ECHO_N "checking for main in -lmysqlpp... $ECHO_C" >&6; }
+if test "${ac_cv_lib_mysqlpp_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmysqlpp  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_mysqlpp_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_mysqlpp_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlpp_main" >&5
+echo "${ECHO_T}$ac_cv_lib_mysqlpp_main" >&6; }
+if test $ac_cv_lib_mysqlpp_main = yes; then
+  CPPFLAGS="$CPPFLAGS -I/usr/include/mysql++ -I/usr/include/mysql"
+     DBSQL_LIBADD="-lmysqlpp"
+
+else
+  { { echo "$as_me:$LINENO: error: library 'MySql++' is required for dbsql" >&5
+echo "$as_me: error: library 'MySql++' is required for dbsql" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -25921,6 +26005,14 @@ else
   BUILD_SCONESITE_IMAGE_FALSE=
 fi
 
+ if test x$DBSQL = xyes; then
+  BUILD_DBSQL_TRUE=
+  BUILD_DBSQL_FALSE='#'
+else
+  BUILD_DBSQL_TRUE='#'
+  BUILD_DBSQL_FALSE=
+fi
+
 
 CPPFLAGS="$CPPFLAGS -Wall"
 
@@ -25979,6 +26071,8 @@ ac_config_files="$ac_config_files lettuce/Makefile"
 ac_config_files="$ac_config_files sconesite/Makefile"
 
 ac_config_files="$ac_config_files sconesite/image/Makefile"
+
+ac_config_files="$ac_config_files dbsql/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -26172,6 +26266,13 @@ if test -z "${BUILD_SCONESITE_IMAGE_TRUE}" && test -z "${BUILD_SCONESITE_IMAGE_F
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_SCONESITE_IMAGE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_SCONESITE_IMAGE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_DBSQL_TRUE}" && test -z "${BUILD_DBSQL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_DBSQL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_DBSQL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -26672,6 +26773,7 @@ do
     "lettuce/Makefile") CONFIG_FILES="$CONFIG_FILES lettuce/Makefile" ;;
     "sconesite/Makefile") CONFIG_FILES="$CONFIG_FILES sconesite/Makefile" ;;
     "sconesite/image/Makefile") CONFIG_FILES="$CONFIG_FILES sconesite/image/Makefile" ;;
+    "dbsql/Makefile") CONFIG_FILES="$CONFIG_FILES dbsql/Makefile" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -26889,6 +26991,7 @@ LIBTOOL!$LIBTOOL$ac_delim
 SSL_LIBADD!$SSL_LIBADD$ac_delim
 SCONESITE_IMAGE_LIBADD!$SCONESITE_IMAGE_LIBADD$ac_delim
 SCONESITE_IMAGE_LDFLAGS!$SCONESITE_IMAGE_LDFLAGS$ac_delim
+DBSQL_LIBADD!$DBSQL_LIBADD$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 BUILD_ROUTER_IP_TRUE!$BUILD_ROUTER_IP_TRUE$ac_delim
 BUILD_ROUTER_IP_FALSE!$BUILD_ROUTER_IP_FALSE$ac_delim
@@ -26910,10 +27013,12 @@ BUILD_SCONESITE_TRUE!$BUILD_SCONESITE_TRUE$ac_delim
 BUILD_SCONESITE_FALSE!$BUILD_SCONESITE_FALSE$ac_delim
 BUILD_SCONESITE_IMAGE_TRUE!$BUILD_SCONESITE_IMAGE_TRUE$ac_delim
 BUILD_SCONESITE_IMAGE_FALSE!$BUILD_SCONESITE_IMAGE_FALSE$ac_delim
+BUILD_DBSQL_TRUE!$BUILD_DBSQL_TRUE$ac_delim
+BUILD_DBSQL_FALSE!$BUILD_DBSQL_FALSE$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 42; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -27544,6 +27649,7 @@ The following modules will be built:
   + examples       $EXAMPLES
   + testbuilder    $TESTBUILDER
   + lettuce        $LETTUCE
+  + dbsql          $DBSQL
 " >&5
 echo "${ECHO_T}
 ------------------------------------------------------------------------------
@@ -27576,4 +27682,5 @@ The following modules will be built:
   + examples       $EXAMPLES
   + testbuilder    $TESTBUILDER
   + lettuce        $LETTUCE
+  + dbsql          $DBSQL
 " >&6; }
